FROM    d.sparta:80/ubuntu:{{TAG}}

# ---------------- #
#   Installation   #
# ---------------- #

ENV DEBIAN_FRONTEND noninteractive

# Install all prerequisites
RUN     apt-get -y install software-properties-common
RUN     add-apt-repository -y ppa:chris-lea/node.js
RUN     apt-get -y update

RUN apt-get -y install python-django-tagging
RUN apt-get install -y python-simplejson
RUN apt-get install -y python-memcache
RUN apt-get install -y python-ldap
RUN apt-get install -y python-cairo
RUN apt-get install -y python-pysqlite2
RUN apt-get install -y python-support
RUN apt-get install -y python-pip
RUN apt-get install -y gunicorn
RUN apt-get install -y supervisor
RUN apt-get install -y nginx-light
RUN apt-get install -y nodejs
RUN apt-get install -y git
RUN apt-get install -y wget
RUN apt-get install -y curl
RUN apt-get install -y openjdk-7-jre
RUN apt-get install -y build-essential
RUN apt-get install -y python-dev

RUN     pip install Twisted==11.1.0
RUN     pip install Django==1.5
RUN     pip install pytz
RUN     npm install ini chokidar

# Checkout the stable branches of Graphite, Carbon and Whisper and install from there
RUN     mkdir /src
RUN     git clone https://github.com/graphite-project/whisper.git /src/whisper            &&\
        cd /src/whisper                                                                   &&\
        git checkout 0.9.x                                                                &&\
        python setup.py install

RUN     git clone https://github.com/graphite-project/carbon.git /src/carbon              &&\
        cd /src/carbon                                                                    &&\
        git checkout 0.9.x                                                                &&\
        python setup.py install


RUN     git clone https://github.com/graphite-project/graphite-web.git /src/graphite-web  &&\
        cd /src/graphite-web                                                              &&\
        git checkout 0.9.x                                                                &&\
        python setup.py install

# Install StatsD
RUN     git clone https://github.com/etsy/statsd.git /src/statsd                                                                        &&\
        cd /src/statsd                                                                                                                  &&\
        git checkout v0.7.2

RUN     apt-get install -y adduser libfontconfig
# Install Grafana
RUN     mkdir /src/grafana                                                                                    &&\
        mkdir /opt/grafana                                                                                    &&\
        wget https://grafanarel.s3.amazonaws.com/builds/grafana_2.6.0_amd64.deb && \
        dpkg -i grafana_2.6.0_amd64.deb && \
        rm /grafana_2.6.0_amd64.deb


# ----------------- #
#   Configuration   #
# ----------------- #

# Confiure StatsD
ADD     docker/grafana/statsd/config.js /src/statsd/config.js

# Configure Whisper, Carbon and Graphite-Web
ADD     docker/grafana/graphite/initial_data.json /opt/graphite/webapp/graphite/initial_data.json
ADD     docker/grafana/graphite/local_settings.py /opt/graphite/webapp/graphite/local_settings.py
ADD     docker/grafana/graphite/carbon.conf /opt/graphite/conf/carbon.conf
ADD     docker/grafana/graphite/storage-schemas.conf /opt/graphite/conf/storage-schemas.conf
ADD     docker/grafana/graphite/storage-aggregation.conf /opt/graphite/conf/storage-aggregation.conf

# Configure Grafana
ADD     docker/grafana/grafana/custom.ini /opt/grafana/conf/custom.ini

# Configure nginx and supervisord
ADD     docker/grafana/nginx/nginx.conf /etc/nginx/nginx.conf
ADD     docker/grafana/supervisord.conf /etc/supervisor/conf.d/supervisord.conf
ADD     docker/grafana/init.sh /init.sh
RUN     chmod +x /init.sh


# ---------------- #
#   Expose Ports   #
# ---------------- #

# Grafana
EXPOSE  80

# StatsD UDP port
EXPOSE  8125/udp

# StatsD Management port
EXPOSE  8126

# Graphite web port
EXPOSE  8000



# -------- #
#   Run!   #
# -------- #

CMD     ["/init.sh"]
